CREATE DATABASE caution_lights;

CREATE USER tom IDENTIFIED BY '123changeme!';
GRANT ALL ON *.* to tom WITH GRANT OPTION;

CREATE USER light_test IDENTIFIED BY '!caution';
GRANT SELECT,UPDATE,INSERT,DELETE,CREATE TEMPORARY TABLES,EXECUTE ON caution_lights.* TO light_test;
